# Generated by Django 6.0.4 on 2026-05-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pack_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager')], default='MR', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='SFA.employee')),
                ('headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.territory')),
            ],
        ),
        migrations.CreateModel(
            name='RCPA_Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_prescribed', models.PositiveIntegerField(help_text="Units sold via Doctor's prescription")),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.chemist')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
        ),
        migrations.CreateModel(
            name='SecondarySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Units ordered by Chemist')),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.chemist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of boxes/units dispatched')),
                ('batch_number', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
        ),
        migrations.AddField(
            model_name='chemist',
            name='linked_stockist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.stockist'),
        ),
        migrations.AddField(
            model_name='stockist',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
    ]
