# Generated by Django 6.0.5 on 2026-06-23 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DailyDCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager'), ('Admin', 'System Administrator')], max_length=5, unique=True)),
                ('hq_da', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('exhq_da', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('outstation_da', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, choices=[('GP', 'General Physician (GP)'), ('Gynecologist', 'Gynecologist (OB/GYN)'), ('Pediatrician', 'Pediatrician (Child Specialist)'), ('Orthopedic', 'Orthopedic (Bone Specialist)'), ('Cardiologist', 'Cardiologist (Heart Specialist)'), ('Dermatologist', 'Dermatologist (Skin Specialist)'), ('Dentist', 'Dentist / Dental Surgeon'), ('Surgeon', 'General Surgeon'), ('ENT', 'ENT Specialist'), ('Psychiatrist', 'Psychiatrist'), ('Ophthalmologist', 'Ophthalmologist (Eye Specialist)'), ('Physician', 'Consultant Physician'), ('Other', 'Other')], max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('degree', models.CharField(blank=True, choices=[('MBBS', 'MBBS'), ('MD', 'MD'), ('MS', 'MS'), ('BAMS', 'BAMS'), ('BHMS', 'BHMS'), ('BDS', 'BDS'), ('MDS', 'MDS'), ('DM', 'DM'), ('MCh', 'MCh'), ('Diploma', 'Diploma (DGO, DCH, etc.)'), ('Other', 'Other')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('dom', models.DateField(blank=True, null=True, verbose_name='Date of Marriage')),
                ('spouse_dob', models.DateField(blank=True, null=True, verbose_name='Spouse Date of Birth')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='doctors/photos/')),
                ('vcard_photo', models.ImageField(blank=True, null=True, upload_to='doctors/vcards/')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('pack_size', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_location_capture', models.BooleanField(default=True, help_text='Isko ON rakhne par MRs location update kar payenge. OFF karne par button gayab ho jayega.')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='TARate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager'), ('Admin', 'System Administrator')], max_length=5, unique=True)),
                ('slab1_upto_km', models.IntegerField(default=100, help_text='Slab 1 upper limit (km)')),
                ('slab1_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='₹/km for Slab 1', max_digits=6)),
                ('slab2_upto_km', models.IntegerField(default=200, help_text='Slab 2 upper limit (km)')),
                ('slab2_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='₹/km for Slab 2', max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DCRVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('chemist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.chemist')),
                ('daily_dcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='SFA.dailydcr')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager'), ('Admin', 'System Administrator')], default='MR', max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='SFA.employee')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('headquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.territory')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee'),
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='SFA.employee')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='SFA.employee')),
            ],
        ),
        migrations.AddField(
            model_name='dailydcr',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee'),
        ),
        migrations.CreateModel(
            name='CompanyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text="Inactive notices won't show on dashboard")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee')),
            ],
        ),
        migrations.AddField(
            model_name='chemist',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee'),
        ),
        migrations.CreateModel(
            name='FreeQtyClaimMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_Manager', 'Pending Manager Approval'), ('Pending_Admin', 'Pending Admin Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=25)),
                ('approved_by_managers', models.JSONField(blank=True, default=list)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_claims', to='SFA.employee')),
                ('stockist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
            options={
                'unique_together': {('employee', 'stockist', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CL', 'Casual Leave (CL)'), ('SL', 'Sick Leave (SL)'), ('PL', 'Privilege/Earned Leave (PL/EL)'), ('LWP', 'Leave Without Pay (LWP)')], max_length=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='SFA.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026)),
                ('cl_total', models.FloatField(default=0.0, verbose_name='Total CL')),
                ('cl_used', models.FloatField(default=0.0, verbose_name='Used CL')),
                ('sl_total', models.FloatField(default=0.0, verbose_name='Total SL')),
                ('sl_used', models.FloatField(default=0.0, verbose_name='Used SL')),
                ('pl_total', models.FloatField(default=0.0, verbose_name='Total PL/EL')),
                ('pl_used', models.FloatField(default=0.0, verbose_name='Used PL/EL')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='SFA.employee')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_expenses', to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('is_modified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PartyWiseSaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_qty', models.IntegerField(default=0)),
                ('free_qty', models.IntegerField(default=0)),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.chemist')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorRxMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapped_billed_qty', models.IntegerField(default=0)),
                ('mapped_free_qty', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('party_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_mappings', to='SFA.partywisesaleline')),
            ],
        ),
        migrations.CreateModel(
            name='PartyWiseSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
            options={
                'unique_together': {('employee', 'stockist', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='partywisesaleline',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='SFA.partywisesalereport'),
        ),
        migrations.CreateModel(
            name='PharmaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending_Manager', 'Pending Manager Approval'), ('Pending_Admin', 'Pending Admin Approval'), ('Approved_Live', 'Approved & Running'), ('Rejected', 'Rejected')], default='Pending_Manager', max_length=20)),
                ('approved_by_managers', models.JSONField(blank=True, default=list, help_text='List of Manager IDs who approved')),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to='SFA.employee')),
            ],
        ),
        migrations.AddField(
            model_name='partywisesaleline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product'),
        ),
        migrations.CreateModel(
            name='DCRProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_detailed', models.BooleanField(default=False)),
                ('sample_qty', models.IntegerField(default=0)),
                ('order_qty', models.IntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='SFA.dcrvisit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('Sample', 'Sample (Medicine)'), ('Routine', 'Routine Input (< ₹1000)'), ('HighValue', 'High-Value Gift (> ₹1000)')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('linked_product', models.ForeignKey(blank=True, help_text='Sirf Sample ke liye product select karein', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromoDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_date', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('In-Transit', 'In-Transit'), ('Received', 'Received by MR')], default='In-Transit', max_length=20)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.promoitem')),
            ],
        ),
        migrations.CreateModel(
            name='GiftCampaignPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.promoitem')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorROILedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.promoitem')),
            ],
        ),
        migrations.CreateModel(
            name='RCPA_Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_prescribed', models.PositiveIntegerField()),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.chemist')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('HQ', 'Headquarter'), ('EX_HQ', 'Ex-Headquarter'), ('OUTSTATION', 'Outstation')], default='HQ', max_length=15)),
                ('distance_from_hq', models.DecimalField(decimal_places=1, default=0.0, help_text='Distance in KM from HQ', max_digits=6)),
                ('status', models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_routes', to='SFA.employee')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.route'),
        ),
        migrations.AddField(
            model_name='dcrvisit',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.route'),
        ),
        migrations.CreateModel(
            name='SecondarySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.chemist')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
        ),
        migrations.CreateModel(
            name='PrimarySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('free_quantity', models.PositiveIntegerField(default=0)),
                ('batch_number', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
        ),
        migrations.CreateModel(
            name='FreeQtyClaimLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_billed_qty', models.IntegerField(default=0)),
                ('total_free_qty', models.IntegerField(default=0)),
                ('claim_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_lines', to='SFA.freeqtyclaimmaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
        ),
        migrations.AddField(
            model_name='chemist',
            name='linked_stockist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.stockist'),
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='SFA.employee')),
            ],
        ),
        migrations.AddField(
            model_name='stockist',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory'),
        ),
        migrations.CreateModel(
            name='DayEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailydcr',
            unique_together={('employee', 'date')},
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_holidays', to='SFA.employee')),
            ],
            options={
                'unique_together': {('date', 'proposed_by')},
            },
        ),
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('territory_category', models.CharField(blank=True, choices=[('HQ', 'Headquarter'), ('EX_HQ', 'Ex-Headquarter'), ('OUTSTATION', 'Outstation'), ('RETURN', 'Return Day')], max_length=15, null=True)),
                ('night_stay', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(decimal_places=1, default=0.0, max_digits=6)),
                ('ta_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('da_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('misc_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('misc_bill', models.ImageField(blank=True, help_text='Bill photo for miscellaneous expense', null=True, upload_to='expense_bills/')),
                ('actual_fare', models.DecimalField(decimal_places=2, default=0.0, help_text='200+ km pe actual travel fare — MR enters at Day End', max_digits=8)),
                ('is_slab3', models.BooleanField(default=False, help_text='True if distance > slab2_upto_km')),
                ('approved_ta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('approved_da', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('approved_misc', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='SFA.employee')),
                ('monthly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_lines', to='SFA.monthlyexpensereport')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyTargetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_Manager', 'Pending Manager'), ('Pending_RSM', 'Pending RSM'), ('Pending_ZSM', 'Pending ZSM'), ('Pending_Admin', 'Pending Admin'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('manager_remark', models.TextField(blank=True, null=True)),
                ('approved_by_managers', models.JSONField(blank=True, default=list)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('target_qty', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
            options={
                'verbose_name': 'Employee Target',
                'verbose_name_plural': 'Employee Targets',
                'unique_together': {('employee', 'product', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DoctorChemistProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chem_mappings', to='SFA.chemist')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_mappings', to='SFA.doctor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
            options={
                'unique_together': {('doctor', 'chemist', 'product')},
            },
        ),
        migrations.CreateModel(
            name='MRInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.promoitem')),
            ],
            options={
                'unique_together': {('employee', 'item')},
            },
        ),
        migrations.CreateModel(
            name='DailyTourPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='SFA.monthlytourprogram')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route')),
            ],
            options={
                'unique_together': {('mtp', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockistProductStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('opening_qty', models.IntegerField(default=0)),
                ('received_qty', models.IntegerField(default=0)),
                ('sale_qty', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockist_statements', to='SFA.employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='SFA.stockist')),
            ],
            options={
                'unique_together': {('stockist', 'product', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='HQDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=1, default=0.0, help_text='Distance between two HQs in KM', max_digits=6)),
                ('from_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_from', to='SFA.territory')),
                ('to_territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transit_to', to='SFA.territory')),
            ],
            options={
                'verbose_name': 'HQ to HQ Distance',
                'verbose_name_plural': 'HQ to HQ Distances',
                'unique_together': {('from_territory', 'to_territory')},
            },
        ),
        migrations.CreateModel(
            name='DayStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('night_stay', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('work_type', models.CharField(choices=[('Field Work', 'Field Work'), ('Meeting', 'Meeting'), ('Transit', 'Transit'), ('Holiday', ' Holiday'), ('Leave', 'Leave'), ('Strike', 'Strike')], default='Field Work', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('joint_worked_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joint_days', to='SFA.employee')),
                ('routes', models.ManyToManyField(blank=True, to='SFA.route')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SFA.territory')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
