# Generated by Django 6.0.5 on 2026-05-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='allocated_to',
            field=models.ForeignKey(blank=True, help_text='Kis MR ka chemist hai?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='allocated_to',
            field=models.ForeignKey(blank=True, help_text='Kis MR ka doctor hai?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
