# Generated by Django 6.0.5 on 2026-05-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0002_chemist_allocated_to_doctor_allocated_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory')),
            ],
        ),
        migrations.AddField(
            model_name='chemist',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.route'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.route'),
        ),
    ]
