# Generated by Django 6.0.5 on 2026-06-24 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0002_alter_dayend_latitude_alter_dayend_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcrvisit',
            name='geofence_bypassed',
            field=models.BooleanField(default=False, help_text='True if backdated entry is made without location punch'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dcr_lock_days',
            field=models.PositiveIntegerField(default=3, help_text='Pichle kitne din tak ka DCR bharne ki permission hai? (Default: 3)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='expense_submit_deadline_day',
            field=models.PositiveIntegerField(default=4, help_text='Pichle mahine ka Expense submit karne ki aakhiri tareekh (Default: 4th)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='manager_pending_approval_block',
            field=models.BooleanField(default=True, help_text='ON (True): Agar Manager ke paas team approvals pending hain, toh Manager ka DCR block hoga.'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='mtp_approval_deadline_day',
            field=models.PositiveIntegerField(default=25, help_text='Agale mahine ka Tour Plan submit karne ki aakhiri tareekh (Default: 25th)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='sale_upload_deadline_day',
            field=models.PositiveIntegerField(default=4, help_text='Pichle mahine ki Secondary Sale/Rx submit karne ki aakhiri tareekh (Default: 4th)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='strict_geofence_for_backdate',
            field=models.BooleanField(default=False, help_text='OFF (False): Backdate DCR bina location ke bhar sakte hain (Exceptions track honge).'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='target_approval_deadline_day',
            field=models.PositiveIntegerField(default=4, help_text='Is mahine ka Target approve hone ki aakhiri tareekh (Default: 4th)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='without_tourplan_dcr_block',
            field=models.BooleanField(default=True, help_text='ON (True): Agar MTP submit nahi hai, toh DCR block ho jayega.'),
        ),
        migrations.CreateModel(
            name='DailyDCRStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_open', models.BooleanField(default=True, help_text='Kya is din ka DCR bharna allowed hai?')),
                ('is_submitted', models.BooleanField(default=False, help_text='Day End hone par True ho jayega')),
                ('is_admin_unlocked', models.BooleanField(default=False, help_text='Admin Override (True karne par auto-block bypass ho jayega)')),
                ('day_type', models.CharField(default='Working', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'verbose_name_plural': 'Daily DCR Statuses',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
