# Generated by Django 6.0.5 on 2026-05-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0003_route_chemist_route_doctor_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
