# Generated by Django 6.0.5 on 2026-06-24 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0003_dcrvisit_geofence_bypassed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydcrstatus',
            name='unlocked_until',
            field=models.DateField(blank=True, help_text='Is date tak unlock valid hai. Iske baad khud-ba-khud wapas lock ho jayega. (Khud bhar na karein, save par auto-set hota hai)', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Employee ki company join karne ki date. DCR calendar isी date se aage hi banega, pehle ka nahi.'),
        ),
        migrations.AlterField(
            model_name='dailydcrstatus',
            name='is_admin_unlocked',
            field=models.BooleanField(default=False, help_text='Admin Override (True karne par 1 din ke liye auto-block bypass ho jayega)'),
        ),
    ]
