# Generated by Django 6.0.5 on 2026-06-24 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0004_dailydcrstatus_unlocked_until_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorroiledger',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='Kis visit ke through ye gift diya gaya. Visit delete hone par yahan se inventory reverse karne ke liye zaroori hai.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roi_entries', to='SFA.dcrvisit'),
        ),
    ]
