# Generated by Django 6.0.5 on 2026-05-16 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0004_tourprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.chemist')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.doctor')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route')),
            ],
        ),
        migrations.CreateModel(
            name='DCRProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_detailed', models.BooleanField(default=False)),
                ('sample_qty', models.IntegerField(default=0)),
                ('order_qty', models.IntegerField(default=0)),
                ('dcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='SFA.dcr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
        ),
        migrations.CreateModel(
            name='DayEnd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
