# Generated by Django 6.0.5 on 2026-05-16 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0005_dcr_dcrproductdetail_dayend'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayStart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.territory')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
