# Generated by Django 6.0.5 on 2026-06-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0005_doctorroiledger_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='free_claim_deadline_day',
            field=models.PositiveIntegerField(default=4, help_text='Pichle mahine ka Free Claim generate/submit karne ki aakhiri tareekh (Default: 4th)'),
        ),
    ]
