# Generated by Django 6.0.5 on 2026-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0006_daystart'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcr',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
