# Generated by Django 6.0.5 on 2026-05-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0007_dcr_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='daystart',
            name='routes',
            field=models.ManyToManyField(blank=True, help_text='Planned and Extra Routes for the day', to='SFA.route'),
        ),
    ]
