# Generated by Django 6.0.5 on 2026-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0007_chemisteditrequest_doctoreditrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
