# Generated by Django 6.0.5 on 2026-05-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0008_daystart_routes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='1 to 12 (e.g., 5 for May)')),
                ('year', models.IntegerField(help_text='e.g., 2026')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='DailyTourPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route')),
                ('mtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='SFA.monthlytourprogram')),
            ],
            options={
                'unique_together': {('mtp', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='TourProgram',
        ),
    ]
