# Generated by Django 6.0.5 on 2026-06-26 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0008_doctoreditrequest_req_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/requests/'),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.territory'),
        ),
    ]
