# Generated by Django 6.0.5 on 2026-05-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0009_monthlytourprogram_dailytourplan_delete_tourprogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcrproductdetail',
            name='dcr',
        ),
        migrations.CreateModel(
            name='DailyDCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
            ],
            options={
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DCRVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chemist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.chemist')),
                ('daily_dcr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='SFA.dailydcr')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.doctor')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.route')),
            ],
        ),
        migrations.AddField(
            model_name='dcrproductdetail',
            name='visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='SFA.dcrvisit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DCR',
        ),
    ]
