# Generated by Django 6.0.5 on 2026-06-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0009_doctoreditrequest_req_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_dom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_spouse_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_vcard_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_vcards_requests/'),
        ),
    ]
