# Generated by Django 6.0.5 on 2026-06-27 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0010_doctoreditrequest_req_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Employee ka home address', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False matlab ye employee company chhod chuka hai ya inactive hai.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leaving_date',
            field=models.DateField(blank=True, help_text='Employee ke company chhodne ki tareekh.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, help_text='Employee ki profile photo', null=True, upload_to='employee_photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Employee ki company join karne ki date. DCR calendar is date se aage hi banega, pehle ka nahi.'),
        ),
    ]
