# Generated by Django 6.0.5 on 2026-06-27 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0011_employee_address_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlytargetmaster',
            options={'verbose_name': 'Monthly Target Master', 'verbose_name_plural': 'Monthly Target Masters'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlytargetmaster',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlytargetmaster',
            name='territory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_target_masters', to='SFA.territory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='monthlytargetmaster',
            name='month',
            field=models.IntegerField(help_text='Month in number (e.g., 1 for Jan, 5 for May)'),
        ),
        migrations.CreateModel(
            name='TerritoryTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month in number (e.g., 1 for Jan, 5 for May)')),
                ('year', models.IntegerField()),
                ('target_qty', models.IntegerField(default=0)),
                ('target_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of target (Qty * Price)', max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='SFA.territory')),
            ],
            options={
                'verbose_name': 'HQ / Territory Target',
                'verbose_name_plural': 'HQ / Territory Targets',
                'unique_together': {('territory', 'product', 'month', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='EmployeeTarget',
        ),
        migrations.RemoveField(
            model_name='monthlytargetmaster',
            name='employee',
        ),
    ]
