# Generated by Django 6.0.5 on 2026-06-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0012_alter_monthlytargetmaster_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlytargetmaster',
            unique_together={('territory', 'month', 'year')},
        ),
    ]
