# Generated by Django 6.0.5 on 2026-06-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0013_alter_monthlytargetmaster_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_employee_name', models.CharField(max_length=255)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
                ('new_employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='SFA.employee')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_executed', to='SFA.employee')),
            ],
            options={
                'verbose_name': 'Employee Transfer Log',
                'verbose_name_plural': 'Employee Transfer Logs',
            },
        ),
    ]
