# Generated by Django 6.0.5 on 2026-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0014_employeetransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Transferred', 'Transferred'), ('Retired', 'Retired'), ('Terminated', 'Terminated')], default='Active', max_length=20),
        ),
    ]
