# Generated by Django 6.0.5 on 2026-06-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0015_employee_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text="True = ye ek 'Vacant_<HQ>' dummy employee hai, asli insaan nahi. Joint Work me normal employee jaisa hi treat hota hai (use individual hi maana jayega)."),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('retired', 'Retired'), ('transferred', 'Transferred'), ('terminated', 'Terminated'), ('vacant', 'Vacant (Placeholder)'), ('archived', 'Archived (Old Dummy)')], default='active', help_text='is_active sirf access/login control karta hai; ye field WAJAH/reason batata hai.', max_length=15),
        ),
        migrations.DeleteModel(
            name='EmployeeTransferLog',
        ),
    ]
