# Generated by Django 6.0.5 on 2026-06-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0016_employee_is_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_employee_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='SFA.employee')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_made', to='SFA.employee')),
            ],
        ),
    ]
