# Generated by Django 6.0.5 on 2026-06-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0017_employeetransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='child_1_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Child 1 Date of Birth'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='child_2_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Child 2 Date of Birth'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='residential_address',
            field=models.TextField(blank=True, null=True, verbose_name='Residential Address'),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_child_1_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_child_2_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoreditrequest',
            name='req_residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
