# Generated by Django 6.0.5 on 2026-06-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0018_doctor_child_1_dob_doctor_child_2_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='gst_slab',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=12),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='ptr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
