# Generated by Django 6.0.5 on 2026-06-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0019_remove_product_price_product_gst_slab_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='chemist',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
