# Generated by Django 6.0.5 on 2026-06-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0020_chemist_latitude_chemist_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemist',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='chemist',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='daystart',
            name='work_type',
            field=models.CharField(choices=[('Field Work', 'Field Work'), ('Meeting', 'Meeting'), ('Transit', 'Transit'), ('Strike', 'Strike')], default='Field Work', max_length=20),
        ),
    ]
