# Generated by Django 6.0.5 on 2026-07-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0021_remove_chemist_latitude_remove_chemist_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_current_month_mtp',
            field=models.BooleanField(default=False, help_text='ON (True): Current month ka MTP bhi add karne dega (deadline ke baad bhi). Testing/exception ke liye.'),
        ),
    ]
