# Generated by Django 6.0.5 on 2026-07-06 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0025_chemist_company_companynotice_company_darate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemist',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chemists', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companynotice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='darate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='da_rates', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hqdistance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hq_distances', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promoitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_items', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockist',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stockists', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarate',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ta_rates', to='SFA.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='territory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='SFA.company'),
            preserve_default=False,
        ),
    ]
