# Generated by Django 6.0.5 on 2026-07-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0026_alter_chemist_company_alter_companynotice_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='address',
            field=models.TextField(blank=True, help_text='Chemist shop address', null=True),
        ),
    ]
