# Generated by Django 6.0.5 on 2026-07-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0027_chemist_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemisteditrequest',
            name='req_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
