# Generated by Django 6.0.5 on 2026-07-11 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0028_chemisteditrequest_req_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='SFA.company'),
        ),
    ]
