# Generated by Django 6.0.5 on 2026-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0030_chemist_latitude_chemist_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='enable_offline_mode',
            field=models.BooleanField(default=True, help_text='Enable to allow the app to save data locally and sync when online. Disable to force online-only data submission.'),
        ),
    ]
