# Generated by Django 6.0.5 on 2026-07-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0033_internalmessage_messageattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partywisesaleline',
            name='chemist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.chemist'),
        ),
    ]
