# Generated by Django 6.0.5 on 2026-07-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0035_employee_anniversary_employee_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemist',
            name='card_photo',
            field=models.ImageField(blank=True, help_text='Chemist ki visiting card ki photo', null=True, upload_to='chemist_cards/'),
        ),
        migrations.AddField(
            model_name='chemist',
            name='owner_dob',
            field=models.DateField(blank=True, help_text='Owner ki date of birth', null=True),
        ),
        migrations.AddField(
            model_name='chemist',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Chemist shop owner ka naam', max_length=150, null=True),
        ),
    ]
