# Generated by Django 6.0.5 on 2026-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0037_internalmessage_all_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydcrstatus',
            name='is_admin_unlocked',
            field=models.BooleanField(default=False, help_text='Admin Override (True karne par 1 din ke liye auto-block bypass ho bypass ho jayega)'),
        ),
        migrations.AlterField(
            model_name='darate',
            name='designation',
            field=models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager'), ('Admin', 'System Administrator')], max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tarate',
            name='designation',
            field=models.CharField(choices=[('MR', 'Medical Representative'), ('ABM', 'Area Business Manager'), ('RBM', 'Regional Business Manager'), ('ZBM', 'Zonal Business Manager'), ('NSM', 'National Sales Manager'), ('Admin', 'System Administrator')], max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='darate',
            unique_together={('company', 'designation')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('territory', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tarate',
            unique_together={('company', 'designation')},
        ),
        migrations.AlterUniqueTogether(
            name='territory',
            unique_together={('company', 'name')},
        ),
    ]
