# Generated by Django 6.0.5 on 2026-08-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0038_alter_dailydcrstatus_is_admin_unlocked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyStockistSaleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_ending_date', models.DateField()),
                ('total_sec_sale_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_closing_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.employee')),
                ('stockist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.stockist')),
            ],
            options={
                'unique_together': {('stockist', 'week_ending_date')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyStockistSaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_sale_qty', models.PositiveIntegerField(default=0)),
                ('closing_qty', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='SFA.weeklystockistsalemaster')),
            ],
        ),
        migrations.CreateModel(
            name='FocusProductTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SFA.employee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
            ],
            options={
                'unique_together': {('company', 'product')},
            },
        ),
    ]
