# Generated by Django 6.0.5 on 2026-08-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0039_weeklystockistsalemaster_weeklystockistsaledetail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_weekly_focus_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_control', to='SFA.employee')),
            ],
        ),
    ]
