# Generated by Django 6.0.5 on 2026-08-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0041_fieldevent_eventphoto_eventcomment_eventlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='allow_mr_primary_sale',
            field=models.BooleanField(default=False, help_text='ON (True): MRs apne Request Hub se Primary Sale (Stockist Order) add kar payenge.'),
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='photo',
            field=models.FileField(upload_to='event_photos/'),
        ),
    ]
