# Generated by Django 6.0.5 on 2026-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0042_systemsetting_allow_mr_primary_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_digital_va_enabled',
            field=models.BooleanField(default=False, help_text='SaaS Admin control: Enable or Disable the Digital VA module for this company.'),
        ),
    ]
