# Generated by Django 6.0.5 on 2026-09-01 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0043_company_is_digital_va_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcrvisit',
            name='is_digital_detailing',
            field=models.BooleanField(default=False, help_text='True agar is visit mein Digital Visual Aid use kiya gaya tha'),
        ),
        migrations.CreateModel(
            name='VAScreenTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.PositiveIntegerField(default=0, help_text='Total time spent on this product in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SFA.product')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='va_screen_times', to='SFA.dcrvisit')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVAMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slide ka naam ya title', max_length=150)),
                ('file', models.FileField(help_text='Digital VA ki image ya document', upload_to='va_media/')),
                ('slide_order', models.PositiveIntegerField(default=1, help_text='Slide dikhane ka sequence (1, 2, 3...)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='va_medias', to='SFA.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='va_slides', to='SFA.product')),
            ],
            options={
                'ordering': ['product', 'slide_order'],
                'unique_together': {('product', 'slide_order')},
            },
        ),
    ]
