# Generated by Django 6.0.5 on 2026-09-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFA', '0044_dcrvisit_is_digital_detailing_vascreentime_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='focusproducttracking',
            unique_together={('company', 'product', 'added_by')},
        ),
    ]
